### ISSUE TITLE
proxy should provide a database link

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cf-mysql-release#150]
If I am using the proxy to connect to my database, I cannot use BOSH links and must provide the port information directly in my other jobs' properties. Because the proxy is effectively a database (by virtue of acting as the front of a database) it should provide a link that my other jobs can consume.

**Comment by drich10** [comment]
Suggested formats:

```
provides:
- name: mysql-proxy
  type: mysql
  properties:
  - port
```

If properties are not renamed before this work is done:

```
provides:
- name: mysql-proxy
  type: mysql
  properties:
  - cf_mysql.mysql.port
```
