### ISSUE TITLE
Provide `type: servicebroker` link

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cf-mysql-release#153]
Currently `cf-mysql-broker` job provides `type: broker` and does not expose any properties.

```
produces:
- name: broker
  type: broker
```

I've been working on several community releases that want to consume service broker jobs - https://github.com/cloudfoundry-community/broker-registrar-boshrelease/releases/tag/v3.0.0 and am currently upgrading `cf-subway-boshrelease` (https://github.com/cloudfoundry-community/cf-subway-boshrelease/blob/9bab12f0eb0627fb6a766b349f11ee45554d5630/jobs/subway-broker/templates/data/properties.sh.erb)

I would like to propose a convention for how service broker jobs provide/describe their link:

```
provides: yaml
- name: cf-mysql-broker
  type: servicebroker
  properties:
  - username
  - password
  - port          # if not :80/:443 based on protocol
  - name       # under what name would broker like to be registered with cf?
  - protocol      # or ssl_enabled
  - external_host # or host
```

And a consumer would look up the link like:

```ruby
<%
  broker = link("servicebroker")
  protocol = broker.p("protocol", broker.p("ssl_enabled", false) ? "https" : "http")
  username = broker.p("username")
  password = broker.p("password")
  host = broker.p("external_host", broker.p("host", broker.instances.first.address))
  uri = "#{protocol}://#{username}:#{password}@#{host}"
  broker.if_p("port") do |broker_port|
    uri += ":#{broker_port}"
  end
-%>
```

The consumer deployment manifest would become sooooo simple:

```yaml
  jobs:
   - name: subway-broker
     release: cf-subway
     consumes:
       servicebroker:
         from: servicebroker
         deployment: docker-broker
```

Whilst this "convention" would be applicable to all service broker BOSH releases, with respect I wanted to start this conversation just with the cf-mysql-release team.

If you're ok with the convention, I am happy to refactor the release (remove the `cf_mysql.broker.` prefix from those properties, etc) and submit a PR.

/cc @cppforlife @menicosia
