### ISSUE TITLE
multi-deployment support

### ISSUE THREAD

**Issue by bkez322** [cloudfoundry/cf-mysql-release#182]
I would like to have deployed a mariadb cluster across multiple azs, each az with its own director. Unless theres a way to deploy to multiple directors in a single deployment, I will have to do multiple deployments. As far as I can tell then, I don't believe there is any way without modifying the release for the mysql-nodes in these separate deployments to replicate, since the config files appear to only load ips from the instances defined in that particular deployment. But I hope I am simply missing something. I am not using AWS.

**Comment by cppforlife** [comment]
that could be done via bosh.io/docs/links-manual to explicitly fulfill
links with particular ips that you pick. come by #bosh in cloudfoundry
slack if it doesnt work out for some reason.

**Comment by bkez322** [comment]
I've done as @cppforlife suggested. When the deployment works the cross-deployment replication works flawlessly. But the deployments I've done this have become very finicky and very frequently (but not always!) fail with the following error in cluster_health_logger_ctl.err.log:

```
[2017-08-24 20:53:36+0000] ------------ STARTING cluster_health_logger_ctl at Thu Aug 24 20:53:36 UTC 2017 --------------
[2017-08-24 20:53:36+0000] 2017/08/24 20:53:36 dial tcp 127.0.0.1:3306: getsockopt: connection refused
```

I'm trying to see if I can identify a pattern for when this happens, but in general it appears to only and consistently occur with non-new deployments. 

I would appreciate any insight into why this may be happening or what I can do to fix it.

**Comment by bkez322** [comment]
Here is one of my interpolated manifests:
```
instance_groups:
- azs:
  - z1
  - z2
  instances: 1
  jobs:
  - consumes:
      mysql:
        instances:
        - address: 10.196.186.146
        - address: 10.196.186.147
    name: mysql
    properties:
      cf_mysql:
        mysql:
          admin_password: m@ri@1
          cluster_health:
            password: m@ri@2
          galera_healthcheck:
            db_password: m@ri@3
            endpoint_password: m@ri@4
          persistent_disk: 50140
          remote_admin_access: true
          seeded_databases:
          - name: grafana
            password: gr@f@n@
            username: grafana
          - name: smoke
            password: sm0ke1
            username: smoke
    release: cf-mysql
  name: mysql
  networks:
  - name: metrix
    static_ips:
    - 10.196.186.146
  persistent_disk: 50140
  stemcell: trusty
  vm_type: medium
- azs:
  - z1
  - z2
  instances: 1
  jobs:
  - name: statsd-proxy
    properties:
      statsd_proxy:
        nodes:
        - '{host: ''10.196.186.141'', port: 9125, adminport: 9126}'
        - '{host: ''10.196.186.142'', port: 9125, adminport: 9126}'
    release: echo-release
  - name: grafana
    properties:
      grafana:
        admin_password: gr4f4n4
        admin_username: grafana
        database:
          host: 10.196.186.146:3306
          name: grafana
          password: gr@f@n@
          type: mysql
          user: grafana
        datasource:
          database_name: any
          database_type: graphite
          name: graphite
          password: any
          url: http://127.0.0.1:8080
          user: any
        listen_port: 80
    release: echo-release
  - name: carbon-cache
    properties:
      carbon_cache:
        filter:
          enable: true
          whitelist:
          - ^ECHO_STATS.*
          - ^TEST.*
          - ^PCF_NONPROD.*
          - ^PCF_SANDBOX.*
          - ^PCF_MOCK.*
          - ^ENTERPRISE_NONPROD.*
          - ^ENTERPRISE_SANDBOX.*
          - ^ENTERPRISE_MOCK.*
    release: echo-release
  - name: carbon-relay
    properties:
      carbon_relay:
        destinations:
        - 10.196.186.141:2004:a
        - 10.196.186.142:2004:b
        line_receiver_port: 2013
        pickle_receiver_port: 2014
        replication_factor: 2
    release: echo-release
  - name: graphite-web
    properties:
      graphite-web:
        db:
          engine: sqlite3
        httpd:
          port: 8080
        time_zone: America/Chicago
        wsgi:
          inactivity-timeout: 60
    release: echo-release
  - name: statsd
    properties:
      statsd:
        nautilus_env: NONE
    release: echo-release
  name: echo-node
  networks:
  - name: metrix
    static_ips:
    - 10.196.186.141
  persistent_disk: 50140
  stemcell: trusty
  vm_type: medium
name: echo-ro98-sm-1
releases:
- name: echo-release
  version: latest
- name: cf-mysql
  version: 36
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3421.11
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-60000
```
