### ISSUE TITLE
cookie_secret property should be a valid BOSH job property

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cf-mysql-release#38]
`cf-mysql-broker` currently contains an invalid job property definition on 
https://github.com/cloudfoundry/cf-mysql-release/blob/master/jobs/cf-mysql-broker/spec#L27

```
properties:
  auth_username:
    description: "Broker's basic auth username"
  auth_password:
    description: "Broker's basic auth password"
  cookie_secret: 'A unique secret key, used to sign sessions'
  ...
```

It should be 

```
properties:
  auth_username:
    description: "Broker's basic auth username"
  auth_password:
    description: "Broker's basic auth password"
  cookie_secret: 
    description: 'A unique secret key, used to sign sessions'
  ...
```
