### ISSUE TITLE
p-mysql broker should expose both proxies for HA

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/cf-mysql-release#82]
The cf-mysql release deploys multiple proxy servers, for HA purpose.
But the cloudfoundry broker exposes only one, exposing the cf app to db access failure during bosh deployment (see below)

Broker should expose the multiple  proxy ips, so that application / buildpacks can leverage the proxy HA

```
+----------------------+---------+--------------------+-----------------+
| Job/index            | State   | Resource Pool      | IPs             |
+----------------------+---------+--------------------+-----------------+
| cf-mysql-broker_z1/0 | running | cf-mysql-broker_z1 | 192.168.100.150 |
| cf-mysql-broker_z2/0 | running | cf-mysql-broker_z2 | 192.168.100.160 |
| mysql_z1/0           | running | mysql_z1           | 192.168.100.155 |
| mysql_z2/0           | running | mysql_z2           | 192.168.100.165 |
| mysql_z3/0           | running | mysql_z3           | 192.168.100.175 |
| proxy_z1/0           | running | proxy_z1           | 192.168.100.156 |
| proxy_z2/0           | running | proxy_z2           | 192.168.100.166 |
+----------------------+---------+--------------------+-----------------+
```

``` yaml
  "p-mysql": [                                                                                     
   {                                                                                               
    "credentials": {                                                                               
     "hostname": "192.168.100.156",                                                                
     "jdbcUrl": "jdbc:mysql://192.168.100.156:3306/cf_c49f7310_121a_44a2_a0e6_315ea501b504?user=k6eGjTLmhoL7kx07\u0026password=zrlNwH2IiMuGwc4v",                                                                                   
     "name": "cf_c49f7310_121a_44a2_a0e6_315ea501b504",                                                           
     "password": "zrlNwH2IiMuGwc4v",                                                                              
     "port": 3306,                                                                                                
     "uri": "mysql://k6eGjTLmhoL7kx07:zrlNwH2IiMuGwc4v@192.168.100.156:3306/cf_c49f7310_121a_44a2_a0e6_315ea501b504?reconnect=true",                                                                                                
     "username": "k6eGjTLmhoL7kx07"                                                                               
    },                                                                                                            
    "label": "p-mysql",                                                                                           
    "name": "testmysql",                                                                                          
    "plan": "100mb",                                                                                              
    "tags": [                                                                                                     
     "mysql"                                                                                                      
    ]                                                                                                             
   }                                                                                                              

```
